=== mrspaceman/RecipeServer/src/main/resources/recipeServer_schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "RecipeServerSchema",
  "description": "A recipe used in the recipe server",
  "type": "object",
  "properties": {
    "id": {
      "description": "a unique id for a recipe",
      "type": "string"
    },
    "name": {
      "description": "the name of a recipe",
      "type": "string"
    },
    "description": {
      "description": "the long description of a recipe",
      "type": "string"
    },
    "serveTime": {
      "type": "string"
    },
    "ingredients": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "description": {
              "type": "string"
            }
          },
          "required": [
            "id",
            "name",
            "description"
          ]
        },
        {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "description": {
              "type": "string"
            }
          },
          "required": [
            "id",
            "name",
            "description"
          ]
        },
        {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "description": {
              "type": "string"
            }
          },
          "required": [
            "id",
            "name",
            "description"
          ]
        },
        {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "description": {
              "type": "string"
            }
          },
          "required": [
            "id",
            "name",
            "description"
          ]
        },
        {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "description": {
              "type": "string"
            }
          },
          "required": [
            "id",
            "name",
            "description"
          ]
        }
      ]
    },
    "steps": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "description": {
              "type": "string"
            },
            "numberMinutesCooking": {
              "type": "integer"
            },
            "numberMinutesStanding": {
              "type": "integer"
            }
          },
          "required": [
            "id",
            "name",
            "description",
            "numberMinutesCooking",
            "numberMinutesStanding"
          ]
        },
        {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "description": {
              "type": "string"
            },
            "numberMinutes": {
              "type": "integer"
            },
            "numberMinutesStanding": {
              "type": "integer"
            }
          },
          "required": [
            "id",
            "name",
            "description",
            "numberMinutes",
            "numberMinutesStanding"
          ]
        }
      ]
    }
  },
  "required": [
    "id",
    "name",
    "description",
    "serveTime",
    "ingredients",
    "steps"
  ]
}

=== mrspaceman/RecipeServer/src/main/resources/roast_chicken_recipe.json
{
  "id": "",
  "name": "Roast Chicken",
  "description": "",
  "serveTime": "13:00",
  "ingredients": [
    {
      "id": "",
      "name": "Whole Chicken",
      "description": ""
    },
    {
      "id": "",
      "name": "Carrots",
      "description": ""
    },
    {
      "id": "",
      "name": "Broccoli",
      "description": ""
    },
    {
      "id": "",
      "name": "Cauliflower",
      "description": ""
    },
    {
      "id": "",
      "name": "Roast Potatoes",
      "description": ""
    }
  ],
  "steps": [
    {
      "id": "",
      "name": "Oven On",
      "description": "Turn oven on to warm up",
      "numberMinutesCooking": 10,
      "numberMinutesStanding": 0
    },
    {
      "id": "",
      "name": "Roast Potatoes",
      "description": "",
      "numberMinutes": 45,
      "numberMinutesStanding": 0
    }
  ]
}
